# Generated by Django 5.2.6 on 2025-09-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('EBAY', 'eBay')], max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fee_flat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='marketlog.item')),
            ],
        ),
    ]
